### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by underworldcryptomarket** [txbits/TxBitsDeployer#2]
I've been working on a project using TxBits. I had no problems with the initial Tx Bits project. I ran into issues using the deployer. Running the deployer will give 2 errors. gen.py and initial_deploy is where the errors come from. This is the output with the errors:

# python3 ./gen.py production.json
creating production/opendkim
sh: 1: opendkim-genkey: not found
Traceback (most recent call last):
  File "/usr/lib/python3.4/shutil.py", line 522, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: 'default.private' -> 'production/opendkim/default.private'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./gen.py", line 204, in <module>
    main()
  File "./gen.py", line 71, in main
    mv('default.private', pfx('opendkim/default.private'))
  File "./gen.py", line 33, in mv
    shutil.move(from_, to)
  File "/usr/lib/python3.4/shutil.py", line 534, in move
    copy2(src, real_dst)
  File "/usr/lib/python3.4/shutil.py", line 244, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.4/shutil.py", line 107, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'default.private'
root@cryptoserver:/home/lordacid/Desktop/Underworld/playbook/secrets# python3 ./gen.py
usage: gen.py [-h] config.json
gen.py: error: the following arguments are required: config.json

./initial_deploy.sh: 8: ./initial_deploy.sh: ansible-playbook: not found

**Comment by BeOleg** [comment]
This project is dead.
Contact me privately for help
contact@onit.ws
